<div align="center">

## <span style="font-size:16pt;">**Wu Qilong**</span>

</div>

## Learning Outcomes

1. To practice with NumPy basics, including broadcasting, reshaping and boolean indexing.
2. To practice with pandas DataFrame creation.
3. To practice and familiarise with pandas DataFrame selection, manipulation and aggregation.

## Tasks

1.  Run the following code to generate an array with shape 5,5,2.

In [19]:
import numpy as np
np.random.seed(19)
x = np.random.randn(5,5,2)

* Take the mean along the 3rd axis. You should get back a matrix with 5 rows and 5 columns.  Let us call it X
* Create an ndarray $Y$ with the following entries. The shape of Y should be (1,5). Perform matrix multiplication Y * X and then reshape your output into shape (5,1).

\begin{equation} Y = 
\begin{pmatrix}
1 & 1 & 1 & 1 & 0 
\end{pmatrix}
\end{equation}

In [20]:
X = x.mean(axis=2)
X

array([[-0.05973087, -0.49089005, -0.42357085,  0.80804857, -0.60506611],
       [-0.6415343 , -0.5084443 , -0.53998122,  0.31112199,  0.18828483],
       [ 0.93247031,  1.40725767,  0.03385096, -0.00910954, -0.11745352],
       [ 1.94792671, -0.75715946, -0.292366  ,  0.69653945, -0.41617049],
       [ 0.29554195,  0.20560918, -0.14319711,  0.32690712,  0.37783195]])

In [21]:
Y = np.array([1, 1, 1, 1, 0]).reshape(1, -1)
Y

array([[1, 1, 1, 1, 0]])

In [22]:
(Y @ X).reshape(5, 1)
# Y.dot(X).reshape(5, 1)

array([[ 2.17913185],
       [-0.34923614],
       [-1.22206711],
       [ 1.80660047],
       [-0.95040528]])

2. Which of the following will run properly, and which will raise errors due to inability to broadcast?

In [23]:
aa = np.arange(0, 10).reshape(2,5)
bb = np.ones(2)

3. A JSON file is a special text format for storing data. It is very similar to a Python dictionary. Take a look at the file `laliga.json`. Use the function `pd.read_json()` to read it into your notebook, and perform the following tasks on it.

    * Extract the rows for Valencia only.
    * Extract the rows for teams that had strictly less than 5 losses.
    * Extract the record for Barcelona in 2011.
    * For each row, compute the number of points the team obtained. A win is worth 3 points, a draw is 1 point, and a loss is 0 points. Store this points total in a new column.
    * Sort the table by year (ascending) and points (descending).
    * Find the average number of points for each team over the three years.

In [2]:
import json
import pandas as pd

# with open("../data/laliga.json") as json_file:
#     json_object = json.load(json_file)
# data = pd.DataFrame(json_object)

data = pd.read_json("../data/laliga.json")
data

Year        Team  Wins  Draws  Losses
0  2010   Barcelona    30      6       2
1  2011   Barcelona    28      7       3
2  2012   Barcelona    32      4       2
3  2010  RealMadrid    29      5       4
4  2011  RealMadrid    32      4       2
5  2012  RealMadrid    26      7       5
6  2010    Valencia    21      8       9
7  2011    Valencia    17     10      11
8  2012    Valencia    19      8      11

In [10]:
# Extract the rows for Valencia only.
data[data['Team'] == 'Valencia']

Year      Team  Wins  Draws  Losses
6  2010  Valencia    21      8       9
7  2011  Valencia    17     10      11
8  2012  Valencia    19      8      11

In [3]:
# Extract the rows for teams that had strictly less than 5 losses.
data[data['Losses'] < 5]

Year        Team  Wins  Draws  Losses
0  2010   Barcelona    30      6       2
1  2011   Barcelona    28      7       3
2  2012   Barcelona    32      4       2
3  2010  RealMadrid    29      5       4
4  2011  RealMadrid    32      4       2

In [12]:
# Extract the record for Barcelona in 2011.
data[(data['Team'] == 'Barcelona') & (data['Year'] == 2011)]

Year       Team  Wins  Draws  Losses
1  2011  Barcelona    28      7       3

In [13]:
# For each row, compute the number of points the team obtained. 
# A win is worth 3 points, a draw is 1 point, and a loss is 0 points. Store this points total in a new column.
data['Points'] = data['Wins'] * 3 + data['Draws'] * 1 + data['Losses'] * 0
data

Year        Team  Wins  Draws  Losses  Points
0  2010   Barcelona    30      6       2      96
1  2011   Barcelona    28      7       3      91
2  2012   Barcelona    32      4       2     100
3  2010  RealMadrid    29      5       4      92
4  2011  RealMadrid    32      4       2     100
5  2012  RealMadrid    26      7       5      85
6  2010    Valencia    21      8       9      71
7  2011    Valencia    17     10      11      61
8  2012    Valencia    19      8      11      65

In [14]:
# Sort the table by year (ascending) and points (descending).
data.sort_values(by=['Year', 'Points'], ascending=[True, False])

Year        Team  Wins  Draws  Losses  Points
0  2010   Barcelona    30      6       2      96
3  2010  RealMadrid    29      5       4      92
6  2010    Valencia    21      8       9      71
4  2011  RealMadrid    32      4       2     100
1  2011   Barcelona    28      7       3      91
7  2011    Valencia    17     10      11      61
2  2012   Barcelona    32      4       2     100
5  2012  RealMadrid    26      7       5      85
8  2012    Valencia    19      8      11      65

In [15]:
# Find the average number of points for each team over the three years.
data.groupby('Team')['Points'].mean()
# data.groupby('Team')['Points'].describe()['mean']

Team
Barcelona     95.666667
RealMadrid    92.333333
Valencia      65.666667
Name: Points, dtype: float64

4. Drop the 2015 rows from the happiness dataset. Now compute the change in Happiness rank for each country (2017 rank - 2016 rank). Select and display the top 10 countries whose ranks improved the most. 

In [4]:
happ = pd.read_csv("../data/happiness_report.csv")
# happ.drop(happ[happ['Year'] == 2015].index, inplace=True)
happ = happ[happ['Year'] != 2015]
happ

Country  Happiness.Rank  Happiness.Score      GDP   Family  \
164        Switzerland             1.0            7.587  1.39651  1.34951   
165            Iceland             2.0            7.561  1.30232  1.40223   
166            Denmark             3.0            7.527  1.32548  1.36058   
167             Norway             4.0            7.522  1.45900  1.33095   
168             Canada             5.0            7.427  1.32629  1.32261   
..                 ...             ...              ...      ...      ...   
487  Somaliland region             NaN              NaN      NaN      NaN   
488               Laos             NaN              NaN      NaN      NaN   
489          Swaziland             NaN              NaN      NaN      NaN   
490           Djibouti             NaN              NaN      NaN      NaN   
491            Comoros             NaN              NaN      NaN      NaN   

     Life.Expectancy  Freedom  Govt.Corruption  Generosity  Dystopia.Residual  \
164          0.94143  0.66557          0.41978     0.29678            2.51738   
165          0.94784  0.62877          0.14145     0.43630            2.70201   
166          0.87464  0.64938          0.48357     0.34139            2.49204   
167          0.88521  0.66973          0.36503     0.34699            2.46531   
168          0.90563  0.63297          0.32957     0.45811            2.45176   
..               ...      ...              ...         ...                ...   
487              NaN      NaN              NaN         NaN                NaN   
488              NaN      NaN              NaN         NaN                NaN   
489              NaN      NaN              NaN         NaN                NaN   
490              NaN      NaN              NaN         NaN                NaN   
491              NaN      NaN              NaN         NaN                NaN   

     Year  
164  2016  
165  2016  
166  2016  
167  2016  
168  2016  
..    ...  
487  2017  
488  2017  
489  2017  
490  2017  
491  2017  

[328 rows x 11 columns]

In [25]:
k = happ.groupby(by=['Country'], group_keys=True).apply(lambda x:x['Happiness.Rank'].diff()).dropna()
dict_k = {key: value for key, value in [(i[0], k[i]) for i in k.index]}
for i, j in enumerate(sorted(dict_k.items(), key=lambda x:x[1])[:10]):
    print(i, j[1], j[0])

0 -35.0 Latvia
1 -31.0 Egypt
2 -29.0 Bulgaria
3 -29.0 Hungary
4 -29.0 Romania
5 -27.0 Senegal
6 -26.0 Cameroon
7 -25.0 Gabon
8 -23.0 Ivory Coast
9 -22.0 Nepal


In [5]:
happ.groupby('Country', group_keys=True).apply(
    lambda x:x.sort_values('Year').diff()).groupby('Country').last().rename(
    columns={'Happiness.Rank': 'Change'})[['Change']].sort_values('Change').head(10).reset_index()

Country  Change
0       Latvia   -35.0
1        Egypt   -31.0
2     Bulgaria   -29.0
3      Hungary   -29.0
4      Romania   -29.0
5      Senegal   -27.0
6     Cameroon   -26.0
7        Gabon   -25.0
8  Ivory Coast   -23.0
9        Nepal   -22.0